# Chapter 1: Getting Ready

1. What does *Portability* mean in the context of programming?  
    The ability of porting to other target.
2. A source code file is in which you wrote code, object file is which the compiler generate from your source code file as mid product but without startup code for different systems and library routines, executable file is generated by the linker who adds library code and start-up code to the final output so it could be read and excuted by the computer as you wish.  
3. The seven major steps in programming:  
    1. Define the Program Objectives
    2. Design the Program
    3. Write the Code
    4. Compile
    5. Run the Program
    6. Test and Debug the Program
    7. Maintain and Modify the Program  
